upstream backend_servers {
    server back-end:5252;
}

upstream frontend_servers {
    server front-end:9000;
}

server {
    listen 80;

    # توجيه طلبات الـ API إلى الباك إند
    location /api {
        proxy_pass http://backend_servers;
    }

    # توجيه بقية الطلبات للفرونت إند
    location / {
        proxy_pass http://frontend_servers;
    }
}
